import { NextIntlClientProvider } from "next-intl";
import type { Metadata } from "next";
import { getMessages } from "next-intl/server";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { ClientToaster } from "@/components/ui/ClientToaster";
import Header from "@/components/globals/Header";
import Footer from "@/components/globals/Footer";
import "../globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

export const metadata: Metadata = {
  // change the icon to the global icon
  icons: {
    icon: "/image0.png",
  },
  title: "Smart Moving head",
  description: "Generated by Smart Moving",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  type Locale = "dk" | "en" | "ar";
  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }
  const messages = await getMessages({ locale });

  return (
    <html dir={locale === "ar" ? "rtl" : "ltr"} lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {/* <ReduxProvider> */}
          <ClientToaster />
          <Header />
          <main className="bg-[#F0F0F0] min-h-screen rounded-tl-[20px] md:rounded-tl-[30px] lg:rounded-tl-[40px] rounded-tr-[20px] md:rounded-tr-[30px] border-b-0 pb-[50px] lg:rounded-tr-[40px]">
            {children}
          </main>
          <Footer />
          {/* <ToastContainer /> */}
          {/* <AutoLogin /> */}
          {/* </ReduxProvider> */}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
